apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app: echo
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - image: inanimate/echo-server
        imagePullPolicy: Always
        name: echo
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: echo
  namespace: default
spec:
  selector:
    app: echo
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
