// +build !ignore_autogenerated

/*
  This is required for deepcopy-gen to work.

This oilerplate will make a lot more sense in the context of Kubernetes, where
all the source code must have a copyright message at the top.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha2

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}
