# Create a kind cluster with 1 control plane and 1 worker node. 
apiVersion: kind.sigs.k8s.io/v1alpha3
kind: Cluster
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  # Map port 80 on the container (worker node) to port 80 on the host.
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
  # Map port 443 on the container (worker node) to port 443 on the host.
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
