apiVersion: v1                                                                  
kind: Pod                                                                       
metadata:                                                                       
  name: my-pod                                                                  
spec:                                                                           
  containers:                                                                   
  - image: ubuntu:18.04                                                         
    name: bash
    args:
    - "sleep"
    - "999"
