apiVersion: apps/v1                                                             
kind: ReplicaSet                                                                
metadata:                                                                       
  name: my-rs                                                                   
spec:                                                                           
  replicas: 2                                                                   
  selector:                                                                     
    matchLabels:                                                                
      app: ubuntu                                                               
  template:                                                                     
    metadata:                                                                   
      labels:                                                                   
        app: ubuntu                                                             
    spec:                                                                       
      containers:                                                               
      - image: ubuntu:18.04                                                     
        name: bash                                                              
        args:                                                                   
        - "sleep"                                                               
        - "999"
